FROM nginxinc/nginx-unprivileged:1-alpine

COPY ./proxy/default.conf /etc/nginx/conf.d/default.conf
# COPY ./uwsgi_params /etc/nginx/uwsgi_params

USER root
RUN mkdir /dist
COPY ./frontend/hack_project/dist /dist
RUN chmod -R 777 /dist/

# RUN mkdir -p /vol/static
# RUN chmod 755 /vol/static

USER nginx
