FROM nginxinc/nginx-unprivileged:1-alpine

COPY ./proxy/default.conf /etc/nginx/conf.d/default.conf
# COPY ./uwsgi_params /etc/nginx/uwsgi_params

USER root
RUN mkdir /front_app
COPY ./frontend/hack_project/front_app /front_app
RUN chmod -R 777 /front_app/

# RUN mkdir -p /vol/static
# RUN chmod 755 /vol/static

USER nginx
