version: '3.7'

services: 
  app:
    build:
      context: .
    # volumes: 
    #   - static_data:/vol/web
    environment: 
      - SECRET_KEY=secretkey123
      - DEBUG=1
      - ALLOWED_HOSTS=*
  proxy:
    build:
      context: ./proxy
    volumes: 
      - static_data:/static
    ports:
      - "80:80"
    depends_on: 
      - app

volumes: 
  static_data:
    